config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  get '/mypage', to: 'mypage#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  has_many :tag_articles, dependent: :destroy
  has_many :articles, through: :tag_articles
end

app/models/tag_article.rb
class TagArticle < ApplicationRecord
  belongs_to :tag
  belongs_to :articles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    skip_before_action :authenticate_user!, only: %i[index show]
    before_action :set_article, only: %i[edit update destroy]

  # GET /articles or /articles.json
  def index
    articles = Article.all
    articles = articles.where("title like ?", "%#{params[:title]}%") if params[:title].present?
    @articles = articles.page params[:page]
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: " #{t('activerecord.models.article')}を作成しました。" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: " #{t('activerecord.models.article')}を作成しました。" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_path, status: :see_other, notice: "#{t('activerecord.models.article')}を作成しました。" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = current_user.articles.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def show
    articles = current_user.articles
    articles = articles.where("title like?", "%#{params[:title]}%") if params[:title].present?

    @articles = articles.page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= article.errors.count%> 件の対応が必要です</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit '保存', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/_search.html.erb
<%= form_with url: articles_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>記事編集</h1>

<%= render 'form', article: @article %>

<%= link_to '詳細', @article %> |
<%= link_to '一覧', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>記事</h1>
<%= render partial: "search" %>
<%= paginate @articles %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td class="hstack gap-3">
          <%= link_to '詳細', article, class: "btn btn-success mr-1" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>記事作成</h1>

<%= render 'form', article: @article %>

<%= link_to '一覧', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header">
    <%= @article.title %>
  </div>
  <div class="card-body">
    <%= @article.content %>
  </div>
</div>
<% if current_user&.id == @article.user_id %>
<%= link_to '編集', edit_article_path(@article), class: "btn btn-warning" %>
<% end %>
<%= link_to '一覧', articles_path, class: "btn btn-secondary" %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "TOP", root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in?%>
          <li class="nav-item">
            <%= link_to "マイページ", mypage_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link active" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "サインアップ", new_user_registration_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "サインイン", new_user_session_path, class: "nav-link active" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WonderfulPostApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/mypage/_search.html.erb
<%= form_with url: mypage_url, method: :get, local: true do |form| %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label 'タイトル', class: "form-label" %>
        <%= form.text_field :title, value: params[:title], class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit '検索', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/mypage/show.html.erb
<p id="notice"><%= notice %></p>

<h1>マイページ</h1>
<%= render partial: "search" %>
<%= paginate @articles %>
<%= link_to '記事作成', new_article_path, class: "btn btn-info" %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">タイトル</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td>
          <%= link_to '詳細', article, class: "btn btn-success" %>
          <%= link_to '編集', edit_article_path(article), class: "btn btn-warning" %>
          <%= link_to '削除', article, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>